mosques = {
    "Masjid Al Noor": "https://mawaqit.net/en/masjid-al-noor-vancouver-98665-united-states",
    "Islamic Center of Boise": "https://mawaqit.net/en/islamic-center-of-boise-boise-83704-united-states",
    "Arden Arcade Community Center": "https://mawaqit.net/en/arden-arcade-community-center-sacramento-95825-united-states",
    "Islamic Center of Mill Valley": "https://mawaqit.net/en/islamic-center-of-millvalley-millvalley-94941-united-states",
    "Masjid Tawheed (NV)": "https://mawaqit.net/en/masjid-tawheed",
    "Islamic Center of North Valley": "https://mawaqit.net/en/islamic-center-of-north-valley-lancaster-93535-united-states",
    "American Islamic Institute of AV": "https://mawaqit.net/en/american-islamic-institute-of-av-palmdale-93550-united-states",
    "MASJID SABIREEN - POMONA": "https://mawaqit.net/en/sabireenmasjid",
    "Fullerton Muslim Community Center": "https://mawaqit.net/en/fullerton-masjid-fullerton-92833-united-states",
    "Masjid Tawheed Center": "https://mawaqit.net/en/masjid-tawheed-center-of-williston-williston-58801-united-states",
    "Islamic Center of Boulder": "https://mawaqit.net/en/islamic-center-of-boulder-boulder-co-80303-united-states",
    "CMCC": "https://mawaqit.net/en/cmcc-colorado-80013-united-states",
    "Islamic Center of Manhattan KS": "https://mawaqit.net/en/islamic-center-of-manhattan-manhattan-66502-united-states",
    "Noor Ul Yaqeen Islamic Center": "https://mawaqit.net/en/noor-ul-yaqeen-islamic-center-kansas-city-missouri-64123-united-states",
    "MASJID AR-RAHMAH (MN)": "https://mawaqit.net/en/masjid-ar-rahmah-owatonna-mn",
    "Dar Abi Bakr": "https://mawaqit.net/en/dar-abi-bakr-mankato-56001-united-states",
    "CENTRAL MN ISLAMIC CENTER": "https://mawaqit.net/en/central-minnesota-islamic-center-st-cloud-56301-united-states",
    "MASJID NUURULIIMAAN مسجد نور الايمان": "https://mawaqit.net/en/masjid-nurul-iman-minneapolis-55404-united-states",
    "Masjid Abu Khadra ICM": "https://mawaqit.net/en/masjid-abu-khadra-icm-columbia-heights-55421-united-states",
    "MASJID SALAAM": "https://mawaqit.net/en/salaam-cultural-center-minneapolis-55418-united-states",
    "Masjid Ibadur Rahman (MN)": "https://mawaqit.net/en/masjid-ibadur-rahman-brooklyn-park-55443-united-states",
    "Darul Arqam Center of Excellence": "https://mawaqit.net/en/darul-arqam-center-of-excellence-blaine-55434-united-states",
    "SHEBOYGAN ISLAMIC CENTER": "https://mawaqit.net/en/sheboygan-islamic-center-oostburg-53070-united-states",
    "LAKE IN THE HILLS": "https://mawaqit.net/en/amco-masjid-lake-in-the-hills-60156-united-states",
    "MASJID ALMUHAJIREEN /AAEC": "https://mawaqit.net/en/aaec-chicago",
    "HOMETOWN MERCY MOSQUE": "https://mawaqit.net/en/hometown-mercy-mosque-hometown-60456-united-states",
    "ISLAMIC CENTER OF WORTH": "https://mawaqit.net/en/worth-mosque-worth-60482-united-states",
    "ISLAMIC CENTER OF NEW ORLEANS": "https://mawaqit.net/en/islamic-center-of-new-orleans-new-orleans-70116-1541-united-states",
    "ISLAMIC CENTER OF MISSISSIPPI & ALABAMA": "https://mawaqit.net/en/islamic-center-of-mississippi-and-alabam-meridian-39301-united-states",
    "SIC MASJID ZAKARIYA": "https://mawaqit.net/en/mohammad-rahman-sterling-heights-48312-united-states",
    "ISLAMIC CULTURAL INSTITUTE": "https://mawaqit.net/en/the-islamic-cultural-institute-st-clair-shores-48082-united-states",
    "ISLAMIC HOUSE OF WISDOM": "https://mawaqit.net/en/islamic-house-of-wisdom-dearborn-heights",
    "TAWHEED CENTER": "https://mawaqit.net/en/tawheed-center-detroit",
    "AMERICAN MOSLEM SOCIETY": "https://mawaqit.net/en/american-moslem-society-kendallville-46755-united-states",
    "MASJID AL QUDS / ICFW": "https://mawaqit.net/en/islamic-center-of-fort-wayne-fort-wayne-46803-united-states",
    "MASJID ABU QASIM": "https://mawaqit.net/en/masjid-abu-qasim-cleveland",
    "NOOR ISLAMIC CULTURAL CENTER": "https://mawaqit.net/en/noor-dublin",
    "POLARIS MASJID": "https://mawaqit.net/en/polaris-masjid-lewis-center-43035-united-states",
    "NOOR ISLAMIC CULTURAL CENTER-NEW ALBANY": "https://mawaqit.net/en/noor-islamic-cultural-center-new-albany-westerville-43081-united-states-4",
    "MASJID ASSALAAMAH": "https://mawaqit.net/en/assalaamah-columbus",
    "DAARUL_AHBAAB دار الأحباب": "https://mawaqit.net/en/islamic-center-of-columbus-ohio-columbus-43231-united-states",
    "ALRAHMA MOSQUE. مسجد الرحمة": "https://mawaqit.net/en/alrahma-mosque-columbus-43224-united-states",
    "MASJID UL BAYYINAH COLUMBUS": "https://mawaqit.net/en/masjid-ul-bayyinah-columbus-columbus-43211-united-states",
    "IBNU TAYMIYAH MASJID AND ISLAMIC CENTER": "https://mawaqit.net/en/ibnutaymiyah-columbus",
    "ABUBAKAR ASIDDIQ ISLAMIC CENTER": "https://mawaqit.net/en/abubakar-columbus",
    "MASJID AL-FURQAN ISLAMIC CENTER": "https://mawaqit.net/en/mosque-al-furqan-columbus",
    "MASJID OUMAR AL FOUTIYOU": "https://mawaqit.net/en/masjid-oumar-al-foutiyou",
    "AL-HUDA ISLAMIC CENTER": "https://mawaqit.net/en/al-huda-islamic-center",
    "MASJID NAMRAH": "https://mawaqit.net/en/masjid-namrah",
    "ISLAMIC CENTER OF MARIETTA": "https://mawaqit.net/en/islamic-center-of-marietta-marietta-45750-united-states",
    "مسجد الرحمن": "https://mawaqit.net/en/arrahmane-dayton-oh",
    "ISLAMIC SOCIETY OF GREATER DAYTON": "https://mawaqit.net/en/islamic-society-of-greater-dayton-sugarcreek-township-45305-united-states",
    "ISLAMIC CENTER OF WESTERN PENNSYLVANIA": "https://mawaqit.net/en/islamic-center-of-western-pennsylvania-wexford-15090-united-states",
    "MUSLIM ASSOCIATION OF GREATER PITTSBURGH": "https://mawaqit.net/en/muslim-association-of-greater-pittsburgh-gibsonia-15044-united-states",
    "BECKLEY MASJID": "https://mawaqit.net/en/islamic-association-of-wv-beckley-beckley-25801-united-states",
    "MASJID MUHAMMAD": "https://mawaqit.net/en/icc",
    "ISGC": "https://mawaqit.net/en/isgc",
    "DALTON ISLAMIC CENTER": "https://mawaqit.net/en/dalton-georgia",
    "ANNISTON ISLAMIC CENTER": "https://mawaqit.net/en/aic-anniston",
    "AL-HEDAYA ISLAMIC CENTER OF ICNA": "https://mawaqit.net/en/alhedaya",
    "مسجد عباد الرحمان MASJID IBAD-UR-RAHMAN": "https://mawaqit.net/en/ibad-ur-rahman",
    "ROSWELL COMMUNITY MASJID": "https://mawaqit.net/en/rcm-roswell",
    "مسجد جعفر": "https://mawaqit.net/en/al-rahmah-alpharetta",
    "MASJID MARYAM": "https://mawaqit.net/en/maryam-duluth",
    "MASJID OMAR BIN ABDUL AZIZ": "https://mawaqit.net/en/masjid-omar-ga",
    "ISLAMIC SOCIETY OF AUGUSTA": "https://mawaqit.net/en/islamic-center-of-augusta-martinez-30907-united-states",
    "MASJID AL IMMAN": "https://mawaqit.net/en/masjid-al-imman-jacksonville-32211-united-states",
    "ISLAMIC CENTER OF NORTHEAST FLORIDA": "https://mawaqit.net/en/islamic-center-of-northeast-florida-jacksonville-32246-united-states",
    "BAYMEADOWS ISLAMIC CENTER (BIC)": "https://mawaqit.net/en/baymeadows-islamic-center-bic-jacksonville-32256-united-states",
    "ISLAMIC CENTER OF ORANGE PARK": "https://mawaqit.net/en/islamic-center-of-orange-park-orange-park-32065-united-states",
    "ISLAMIC CENTER OF ST. AUGUSTINE": "https://mawaqit.net/en/islamic-center-of-st-augustine-st-augustine-32086-united-states",
    "HODA CENTER": "https://mawaqit.net/en/hoda-center-gainesville-42608-united-states",
    "ISLAMIC CENTER OF PALM COAST": "https://mawaqit.net/en/islamic-center-of-palm-coast-bunnell-32110-united-states",
    "ICDB - مسجد المؤمنين": "https://mawaqit.net/en/icdb-msjd-lmwmnyn-daytona-beach-32114-united-states",
    "مسجد مريم": "https://mawaqit.net/en/maryam-debary",
    "MASJID AL-SALAM": "https://mawaqit.net/en/assalam-sanford",
    "HMCC - HEATHROW MUSLIM COMMUNITY CENTER": "https://mawaqit.net/en/hmcc-heathrow-muslim-community-center-lake-mary-32746-united-states",
    "AMCC": "https://mawaqit.net/en/amcc-longwood",
    "OVIEDO MUSALLA": "https://mawaqit.net/en/oviedo-musalla-oviedo-32765-united-states",
    "MUSLIM COMMUNITY CENTER OF APOPKA (MCCA)": "https://mawaqit.net/en/muslim-community-center-of-apopka-mcca-apopka-32703-united-states",
    "MASJID AL-MALIK": "https://mawaqit.net/en/almalik-orlando-florida",
    "MASJID AL-RAHMAN (FL)": "https://mawaqit.net/en/alrahman-orlando-florida",
    "MASJID AL-QUDDUS": "https://mawaqit.net/en/alquds-orlando-florida",
    "MASJID AL-HAQ": "https://mawaqit.net/en/alhaq-orlando-florida",
    "MASJID AL-RAHEEM": "https://mawaqit.net/en/arraheem-orlando-florida",
    "MASJID TAZKIAH": "https://mawaqit.net/en/altazkiah-ocoee",
    "AISHA CENTER": "https://mawaqit.net/en/aisha-cultural-center-orlando-32828-united-states-1",
    "MASJID AL-IHSAAN": "https://mawaqit.net/en/alihsaan-orlando",
    "AL-BUKHARI ISLAMIC CENTER": "https://mawaqit.net/en/al-bukhari-islamic-center-orlando-florida",
    "MASJID AL-AZIZ": "https://mawaqit.net/en/ma-alaziz-orlando-florida",
    "ISLAMIC CENTER OF ORLANDO": "https://mawaqit.net/en/jama-orlando",
    "MASJID ALNOOR KISSIMMEE مسجد النور": "https://mawaqit.net/en/masjid-al-noor-kissimmee-34746-united-states",
    "AMERICAN MUSLIM LEADERSHIP COUNCIL (AML)": "https://mawaqit.net/en/aml",
    "ISLAMIC CENTER OF OSCEOLA INC": "https://mawaqit.net/en/islamic-center-of-osceola-inc-kissimmee-34741-united-states",
    "MASJID TAWHEED (FL)": "https://mawaqit.net/en/masjid-tawheed-kissimmee-fl-kissimmee-34746-united-states",
    "MASJID DARUL ULOOM": "https://mawaqit.net/en/masjid-darul-uloom-kissimmee-34746-united-states-1",
    "LAKE NONA MASJID": "https://mawaqit.net/en/nona-masjid-saint-cloud-34771-united-states",
    "MASJID AS-SUNNAH": "https://mawaqit.net/en/as-sunnah-kissimmee",
    "ALBIR CENTER": "https://mawaqit.net/en/albir-center-kissimmee-34758-united-states",
    "MASJID AL HUDA": "https://mawaqit.net/en/stcloudmasjid",
    "ISLAMIC CENTER OF POINCIANA": "https://mawaqit.net/en/islamic-center-of-poinciana-kissimmee-34746-united-states",
    "MASJID AL MUTAKABER": "https://mawaqit.net/en/masjid-al-mutakaber-winter-haven-florida-33884-united-states",
    "MASJID AL-MUMIN": "https://mawaqit.net/en/almumin-titusville",
    "ISBC": "https://mawaqit.net/en/isbc-melbourne",
    "MASJID AL-JABBAR": "https://mawaqit.net/en/aljabbar-sebring-florida",
    "ASH-SHURAH ISLAMIC CENTER": "https://mawaqit.net/en/al-beshara-islamic-center",
    "ISRA MASJID": "https://mawaqit.net/en/isra-masjid",
    "Islamic Society of Saint Petersburg": "https://mawaqit.net/en/islamic-society-of-saint-petersburg-saint-petersburg",
    "AICF": "https://mawaqit.net/en/aicf-pompano-beach",
    "MASJID TAWHEED WAS-SUNNAH": "https://mawaqit.net/en/masjid-tawheed-was-sunnah-durham-nc-united-states",
    "MASJID AR-RAHMAH (NC)": "https://mawaqit.net/en/masjid-ar-rahmah-elizebeth-city-27909-united-states",
    "ISLAMIC COMMUNITY CENTER": "https://mawaqit.net/en/islamic-community-center-of-vermont-vinooski-05404-united-states",
    "MCBNY": "https://mawaqit.net/en/muslim-community-of-bethlehem-delmar-ny-12077-united-states",
    "MIT MUSALLAH": "https://mawaqit.net/en/mit-musallah-cambridge-02139-united-states-1",
    "ABRICC": "https://mawaqit.net/en/abricc-acton-01720-united-states",
    "WORCESTER ISLAMIC CENTER": "https://mawaqit.net/en/worcester-islamic-center-worcester-01606-united-states",
    "ISGW": "https://mawaqit.net/en/isgw-worcester-01605-united-states",
    "ISLAMIC CENTER OF PRESTON": "https://mawaqit.net/en/icop-islamic-center-of-preston-preston-06365-united-states",
    "ISLAMIC CENTER OF DEER PARK": "https://mawaqit.net/en/islamic-center-of-deer-park-deer-park-11729-united-states",
    "ISLAMIC CENTER OF NEW ROCHELLE": "https://mawaqit.net/en/islamic-center-of-new-rochelle-new-rochelle-10801-united-states",
    "ALMUSTAFA ISLAMIC CENTER": "https://mawaqit.net/en/almustafa-pompton",
    "ISLAMIC CENTER OF ESSEX COUNTY": "https://mawaqit.net/en/islamic-center-of-essex-county-caldwell-07006-united-states",
    "ISLAMIC CENTER OF VERONA-عباد الرحمن": "https://mawaqit.net/en/islamic-center-of-verona-ebadur-rahman-verona",
    "MASJID IBN SINA CENTER": "https://mawaqit.net/en/masjid-ibn-sina-center-queens-11105-united-states",
    "AL-IMAN MOSQUE": "https://mawaqit.net/en/al-iman-mosque-astoria-11103-united-states",
    "ASTORIA ISLAMIC CENTER": "https://mawaqit.net/en/astoria-queens",
    "NORTH HUDSON ISLAMIC EDUCATIONAL CENTER": "https://mawaqit.net/en/nhiec-union-city-nj-07087-united-states",
    "ALHODA ISLAMIC CENTER": "https://mawaqit.net/en/alhoda-islamic-center-jersey-city-07307-united-states",
    "AL TAWHEED CENTER": "https://mawaqit.net/en/al-tawheed-center-jersey-city-07306-united-states",
    "MASJID AS-SALAM INC": "https://mawaqit.net/en/masjid-as-salam-inc-jersey-city-07306-united-states",
    "BROOKLYN ISLAMIC CENTER": "https://mawaqit.net/en/islamic-center-brooklyn",
    "MAS YOUTH CENTER": "https://mawaqit.net/en/myc-brooklyn-brooklyn-11214-united-states",
    "86 ST ISLAMIC CENTER مسجد الرحمن بايريدج": "https://mawaqit.net/en/86-st-islamic-center-msjd-lrhmn-byrydj-brooklyn-11209-united-states",
    "MASJID SALAHUDDIN": "https://mawaqit.net/en/masjid-salahuddin-plainfield-07060-united-states",
    "ISLAMIC CENTER OF EAST BRUNSWICK": "https://mawaqit.net/en/islamic-center-of-east-brunswick-east-brunswick-08816-united-states",
    "ISLAMIC SOCIETY OF SCHUYLKILL COUNTY": "https://mawaqit.net/en/islamic-society-of-schuylkill-county-pottsville-17901-united-states",
    "Islamic Center (Reading, PA)": "https://mawaqit.net/en/icorpa",
    "MASJID AR RAHMAN (PA)": "https://mawaqit.net/en/masjid-ar-rahman-coatesville-19320-united-states",
    "FOUNDATION FOR ISLAMIC EDUCATION": "https://mawaqit.net/en/foundation-for-islamic-education-exton-pa",
    "ISLAMIC SOCIETY CHESTER COUNTY": "https://mawaqit.net/en/islamic-society-of-chester-county-west-chester-19380-united-states",
    "MASJID ALAMIN COMMUNITY CENTER": "https://mawaqit.net/en/masjid-alamin-community-center-philadelphia-19143-united-states",
    "MASJID AL BUKHARI IN PHILADELPHIA": "https://mawaqit.net/en/masjid-al-bukhari-in-philadelphia-philadelphia-19116-united-states",
    "MASJID AL-KAREEM": "https://mawaqit.net/en/masjid-al-kareem-lutherville-21093-united-states",
    "ISLAMIC SOCIETY OF WINCHESTER": "https://mawaqit.net/en/isow",
    "MAKKAH LEARNING CENTER - GAMBRILLS, MD": "https://mawaqit.net/en/mlcmd",
    "MASJID AL-ANSAR - ANNAPOLIS, MD": "https://mawaqit.net/en/isamd",
    "MADANI MASJID": "https://mawaqit.net/en/madani-masjid-chantilly-20152-united-states-1",
    "MASJID AL ISTIQAMAH": "https://mawaqit.net/en/ric20190",
    "UYGHUR ISLAMIC CENTER (CHANTILLY)": "https://mawaqit.net/en/uyghur-islamic-center-chantilly-chantilly-20151-united-states",
    "CLARENDON ISLAMIC CENTER": "https://mawaqit.net/en/clarendon-islamic-center-arlington-22201-united-states",
    "HILAL ISLAMIC CENTER": "https://mawaqit.net/en/hilal-islamic-center-fairfax-22031-united-states",
    "UYGHUR ISLAMIC CENTER (FAIRFAX)": "https://mawaqit.net/en/uyghur-islamic-center-fairfax-22030-united-states",
    "ISLAMIC CENTER OF NORTHERN VIRGINIA": "https://mawaqit.net/en/icnvt",
    "BAITUL MUKARRAM MASJID": "https://mawaqit.net/en/baitul-mukarram-masjid-arlington-22204-united-states",
    "DARUL HIKMAH ISLAMIC CENTER": "https://mawaqit.net/en/darul-hikmah-islamic-center-alexandria-22311-united-states",
    "IQRA LEARNING CENTER": "https://mawaqit.net/en/iqra",
    "MASJID IBADUR-RAHMAN (VA)": "https://mawaqit.net/en/masjid-ibadur-rahman-msjd-bd-lrhmn-springfield-22151-united-states",
    "UMM UL QURA CENTER": "https://mawaqit.net/en/uuqcenter",
    "MADINA ISLAMIC CENTER": "https://mawaqit.net/en/madina-springfield",
    "ICNA VA MASJID": "https://mawaqit.net/en/icna-va-masjid-alexandria-22306-united-states-2",
    "مسجد نور MASJID NOOR": "https://mawaqit.net/en/masjidnoor",
    "MANASSAS MUSLIM ASSOCIATION": "https://mawaqit.net/en/mma",
    "BAITUL MA’MUR ISLAMIC CENTER": "https://mawaqit.net/en/baitul-mamur-islamic-alexandria-22309-united-states",
    "مركز الإيمان AL-IMAN CENTER": "https://mawaqit.net/en/al-iman",
    "DAR ALNOOR ISLAMIC COMMUNITY CENTER": "https://mawaqit.net/en/mav",
    "MADINATUL ULOOM": "https://mawaqit.net/en/mtu",
    "WOODBRIDGE FAITH CENTER": "https://mawaqit.net/en/woodbridge-faith-center-woodbridge-22191-united-states",
    "HASKAY COMMUNITY MASJID": "https://mawaqit.net/en/haskay",
    "DAR AL SALAAM": "https://mawaqit.net/en/dar-al-salaam-woodbridge-22191-united-states",
    "DAR AL BARAKAH": "https://mawaqit.net/en/dar-al-barakah-manassas-20112-united-states",
    "BADR COMMUNITY CENTER OF DUMFRIES": "https://mawaqit.net/en/bccd",
    "ISLAMIC CENTER OF CULPEPER": "https://mawaqit.net/en/culpeper-islamic-center-culpeper-22701-united-states",
    "FREDERICKSBURG MUSLIM COMMUNITY": "https://mawaqit.net/en/fredericksburg-muslim-community-fredericksburg-22401-united-states",
    "ISLAMIC CENTER OF FREDERICKSBURG": "https://mawaqit.net/en/icf",
}
