mosques = {
    "Masjid Al Noor": "https://mawaqit.net/en/masjid-al-noor-vancouver-98665-united-states",
    "Islamic Center of Boise": "https://mawaqit.net/en/islamic-center-of-boise-boise-83704-united-states",
    "Arden Arcade Community Center": "https://mawaqit.net/en/arden-arcade-community-center-sacramento-95825-united-states",
    "Islamic Center of Mill Valley": "https://mawaqit.net/en/islamic-center-of-millvalley-millvalley-94941-united-states",
    "Masjid Tawheed": "https://mawaqit.net/en/masjid-tawheed",
    "Islamic Center of North Valley": "https://mawaqit.net/en/islamic-center-of-north-valley-lancaster-93535-united-states",
    "American Islamic Institute of AV": "https://mawaqit.net/en/american-islamic-institute-of-av-palmdale-93550-united-states",
    "MASJID SABIREEN - POMONA": "https://mawaqit.net/en/sabireenmasjid",
    "Fullerton Muslim Community Center": "https://mawaqit.net/en/fullerton-masjid-fullerton-92833-united-states",
    "Masjid Tawheed Center": "https://mawaqit.net/en/masjid-tawheed-center-of-williston-williston-58801-united-states",
    "Islamic Center of Boulder": "https://mawaqit.net/en/islamic-center-of-boulder-boulder-co-80303-united-states",
    "CMCC": "https://mawaqit.net/en/cmcc-colorado-80013-united-states",
    "Islamic Center of Manhattan KS": "https://mawaqit.net/en/islamic-center-of-manhattan-manhattan-66502-united-states",
    "Noor Ul Yaqeen Islamic Center": "https://mawaqit.net/en/noor-ul-yaqeen-islamic-center-kansas-city-missouri-64123-united-states",
    "MASJID AR-RAHMAH": "https://mawaqit.net/en/masjid-ar-rahmah-owatonna-mn",
    "Dar Abi Bakr": "https://mawaqit.net/en/dar-abi-bakr-mankato-56001-united-states",
    "Central MN Islamic Center": "https://mawaqit.net/en/central-minnesota-islamic-center-st-cloud-56301-united-states",
    "Masjid Nuuruliimaan": "https://mawaqit.net/en/masjid-nurul-iman-minneapolis-55404-united-states",
    "Masjid Abu Khadra ICM": "https://mawaqit.net/en/masjid-abu-khadra-icm-columbia-heights-55421-united-states",
    "MASJID SALAAM": "https://mawaqit.net/en/salaam-cultural-center-minneapolis-55418-united-states",
    "Masjid Ibadur Rahman": "https://mawaqit.net/en/masjid-ibadur-rahman-brooklyn-park-55443-united-states",
    "Darul Arqam Center of Excellence": "https://mawaqit.net/en/darul-arqam-center-of-excellence-blaine-55434-united-states",
    "Sheboygan Islamic Center": "https://mawaqit.net/en/sheboygan-islamic-center-oostburg-53070-united-states",
    "Lake in the Hills": "https://mawaqit.net/en/amco-masjid-lake-in-the-hills-60156-united-states",
    "Masjid AlMuhajireen / AAEC": "https://mawaqit.net/en/aaec-chicago",
    "Hometown Mercy Mosque": "https://mawaqit.net/en/hometown-mercy-mosque-hometown-60456-united-states",
    "Islamic Center of Worth": "https://mawaqit.net/en/worth-mosque-worth-60482-united-states",
    "Islamic Center of New Orleans": "https://mawaqit.net/en/islamic-center-of-new-orleans-new-orleans-70116-1541-united-states",
    "Islamic Center of Mississippi & Alabama": "https://mawaqit.net/en/islamic-center-of-mississippi-and-alabam-meridian-39301-united-states",
    "SIC Masjid Zakariya": "https://mawaqit.net/en/mohammad-rahman-sterling-heights-48312-united-states",
    "Islamic Cultural Institute": "https://mawaqit.net/en/the-islamic-cultural-institute-st-clair-shores-48082-united-states",
    "Islamic House of Wisdom": "https://mawaqit.net/en/islamic-house-of-wisdom-dearborn-heights",
    "Tawheed Center": "https://mawaqit.net/en/tawheed-center-detroit",
    "American Moslem Society": "https://mawaqit.net/en/american-moslem-society-kendallville-46755-united-states",
    "Masjid Al Quds / ICFW": "https://mawaqit.net/en/islamic-center-of-fort-wayne-fort-wayne-46803-united-states",
    "Masjid Abu Qasim": "https://mawaqit.net/en/masjid-abu-qasim-cleveland",
    "Noor Islamic Cultural Center": "https://mawaqit.net/en/noor-dublin",
    "Polaris Masjid": "https://mawaqit.net/en/polaris-masjid-lewis-center-43035-united-states",
    "Noor Islamic Cultural Center-New Albany": "https://mawaqit.net/en/noor-islamic-cultural-center-new-albany-westerville-43081-united-states-4",
    "Masjid Assalaamah": "https://mawaqit.net/en/assalaamah-columbus",
    "Daarul_Ahbaab": "https://mawaqit.net/en/islamic-center-of-columbus-ohio-columbus-43231-united-states",
    "AlRahma Mosque": "https://mawaqit.net/en/alrahma-mosque-columbus-43224-united-states",
    "Masjid Ul Bayyinah Columbus": "https://mawaqit.net/en/masjid-ul-bayyinah-columbus-columbus-43211-united-states",
    "Ibnu Taymiyah Masjid and Islamic Center": "https://mawaqit.net/en/ibnutaymiyah-columbus",
    "Abubakar Asiddiq Islamic Center": "https://mawaqit.net/en/abubakar-columbus",
    "Masjid Al-Furqan Islamic Center": "https://mawaqit.net/en/mosque-al-furqan-columbus",
    "Masjid Oumar Al Foutiyou": "https://mawaqit.net/en/masjid-oumar-al-foutiyou",
    "Al-Huda Islamic Center": "https://mawaqit.net/en/al-huda-islamic-center",
    "Masjid Namrah": "https://mawaqit.net/en/masjid-namrah",
    "Islamic Center of Marietta": "https://mawaqit.net/en/islamic-center-of-marietta-marietta-45750-united-states",
    "Masjid Ar-Rahman": "https://mawaqit.net/en/arrahmane-dayton-oh",
    "Islamic Society of Greater Dayton": "https://mawaqit.net/en/islamic-society-of-greater-dayton-sugarcreek-township-45305-united-states",
    "Islamic Center of Western Pennsylvania": "https://mawaqit.net/en/islamic-center-of-western-pennsylvania-wexford-15090-united-states",
    "Muslim Association of Greater Pittsburgh": "https://mawaqit.net/en/muslim-association-of-greater-pittsburgh-gibsonia-15044-united-states",
    "Beckley Masjid": "https://mawaqit.net/en/islamic-association-of-wv-beckley-beckley-25801-united-states",
    "Masjid Muhammad": "https://mawaqit.net/en/icc",
    "ISGC": "https://mawaqit.net/en/isgc",
    "Dalton Islamic Center": "https://mawaqit.net/en/dalton-georgia",
    "Anniston Islamic Center": "https://mawaqit.net/en/aic-anniston",
    "Al-Hedaya Islamic Center of ICNA": "https://mawaqit.net/en/alhedaya",
    "Masjid Ibad-ur-Rahman": "https://mawaqit.net/en/ibad-ur-rahman",
    "Roswell Community Masjid": "https://mawaqit.net/en/rcm-roswell",
    "Masjid Jafar": "https://mawaqit.net/en/al-rahmah-alpharetta",
    "Masjid Maryam": "https://mawaqit.net/en/maryam-duluth",
    "Masjid Omar bin Abdul Aziz": "https://mawaqit.net/en/masjid-omar-ga",
    "Islamic Society of Augusta": "https://mawaqit.net/en/islamic-center-of-augusta-martinez-30907-united-states",
    "Masjid Al Imman": "https://mawaqit.net/en/masjid-al-imman-jacksonville-32211-united-states",
    "Islamic Center of Northeast Florida": "https://mawaqit.net/en/islamic-center-of-northeast-florida-jacksonville-32246-united-states",
    "Baymeadows Islamic Center (BIC)": "https://mawaqit.net/en/baymeadows-islamic-center-bic-jacksonville-32256-united-states",
    "Islamic Center of Orange Park": "https://mawaqit.net/en/islamic-center-of-orange-park-orange-park-32065-united-states",
    "Islamic Center of St. Augustine": "https://mawaqit.net/en/islamic-center-of-st-augustine-st-augustine-32086-united-states",
    "Hoda Center": "https://mawaqit.net/en/hoda-center-gainesville-42608-united-states",
    "Islamic Center of Palm Coast": "https://mawaqit.net/en/islamic-center-of-palm-coast-bunnell-32110-united-states",
    "ICDB - Masjid Al-Mu'mineen": "https://mawaqit.net/en/icdb-msjd-lmwmnyn-daytona-beach-32114-united-states",
    "Masjid Maryam (Debary)": "https://mawaqit.net/en/maryam-debary",
    "Masjid Al-Salam": "https://mawaqit.net/en/assalam-sanford",
    "HMCC - Heathrow Muslim Community Center": "https://mawaqit.net/en/hmcc-heathrow-muslim-community-center-lake-mary-32746-united-states",
    "AMCC": "https://mawaqit.net/en/amcc-longwood",
    "Oviedo Musalla": "https://mawaqit.net/en/oviedo-musalla-oviedo-32765-united-states",
    "Muslim Community Center of Apopka (MCCA)": "https://mawaqit.net/en/muslim-community-center-of-apopka-mcca-apopka-32703-united-states",
    "Masjid Al-Malik": "https://mawaqit.net/en/almalik-orlando-florida",
    "Masjid Al-Rahman": "https://mawaqit.net/en/alrahman-orlando-florida",
    "Masjid Al-Quddus": "https://mawaqit.net/en/alquds-orlando-florida",
    "Masjid Al-Haq": "https://mawaqit.net/en/alhaq-orlando-florida",
    "Masjid Al-Raheem": "https://mawaqit.net/en/arraheem-orlando-florida",
    "Masjid Tazkiah": "https://mawaqit.net/en/altazkiah-ocoee",
    "Aisha Center": "https://mawaqit.net/en/aisha-cultural-center-orlando-32828-united-states-1",
    "Masjid Al-Ihsaan": "https://mawaqit.net/en/alihsaan-orlando",
    "Al-Bukhari Islamic Center": "https://mawaqit.net/en/al-bukhari-islamic-center-orlando-florida",
    "Masjid Al-Aziz": "https://mawaqit.net/en/ma-alaziz-orlando-florida",
    "Islamic Center of Orlando": "https://mawaqit.net/en/jama-orlando",
    "Masjid AlNoor Kissimmee": "https://mawaqit.net/en/masjid-al-noor-kissimmee-34746-united-states",
    "American Muslim Leadership Council (AML)": "https://mawaqit.net/en/aml",
    "Islamic Center of Osceola Inc": "https://mawaqit.net/en/islamic-center-of-osceola-inc-kissimmee-34741-united-states",
    "Masjid Tawheed (Kissimmee)": "https://mawaqit.net/en/masjid-tawheed-kissimmee-fl-kissimmee-34746-united-states",
    "Masjid Darul Uloom": "https://mawaqit.net/en/masjid-darul-uloom-kissimmee-34746-united-states-1",
    "Lake Nona Masjid": "https://mawaqit.net/en/nona-masjid-saint-cloud-34771-united-states",
    "Masjid As-Sunnah": "https://mawaqit.net/en/as-sunnah-kissimmee",
    "Albir Center": "https://mawaqit.net/en/albir-center-kissimmee-34758-united-states",
    "Masjid Al Huda": "https://mawaqit.net/en/stcloudmasjid",
    "Islamic Center of Poinciana": "https://mawaqit.net/en/islamic-center-of-poinciana-kissimmee-34746-united-states",
    "Masjid Al Mutakaber": "https://mawaqit.net/en/masjid-al-mutakaber-winter-haven-florida-33884-united-states",
    "Masjid Al-Mumin": "https://mawaqit.net/en/almumin-titusville",
    "ISBC": "https://mawaqit.net/en/isbc-melbourne",
    "Masjid Al-Jabbar": "https://mawaqit.net/en/aljabbar-sebring-florida",
    "Ash-Shurah Islamic Center": "https://mawaqit.net/en/al-beshara-islamic-center",
    "ISRA Masjid": "https://mawaqit.net/en/isra-masjid",
    "Islamic Society of Saint Petersburg": "https://mawaqit.net/en/islamic-society-of-saint-petersburg-saint-petersburg",
    "AICF": "https://mawaqit.net/en/aicf-pompano-beach",
}
